
const mongoose = require("mongoose");

// const BoardSchema = require("./board");

const UserSchema = new mongoose.Schema({
  name: String,
  googleid: String,
});

const PixelSchema = new mongoose.Schema({
  color: String,
  filled: Boolean,
});

const BoardSchema  = new mongoose.Schema({
  _id: String,
  width: Number,
  height: Number,
  pixels: [{
      type: PixelSchema,
  }],
})

//define a game schema for the database
const GameSchema = new mongoose.Schema({
  _id: String,
  host_id: String, // links to the _id of the host user (_id is an autogenerated field by Mongoose).
  players: [UserSchema],
  pixelers: [UserSchema],
  board: BoardSchema,
  started: Boolean,
  finished: Boolean,
  wordpack: String,
  word: String,
  guesses: [String],
  guesser: String,
});

// compile model from schema
module.exports = mongoose.model("game", GameSchema);
